//! The themes that shipped before parks: a straight transcription of the old
//! `palette()` match into data. Ids are load-bearing — they live in users'
//! `config.json` — so none may be renamed, including the `gruvbox` /
//! `gruvbox-light` inconsistency.

use super::{rgb, rgb3, Origin, Palette, Theme, ThemeKind};
use ratatui::style::Color;

pub static BUILTIN: &[Theme] = &[
    Theme {
        id: "dark",
        name: "Dark (terminal colors)",
        kind: ThemeKind::Dark,
        origin: Origin::Builtin,
        keywords: "default ansi terminal",
        // Sticks to ANSI colors so it follows the terminal's own scheme.
        palette: Palette {
            text: Color::White,
            dim: Color::DarkGray,
            border: Color::DarkGray,
            warn: Color::Yellow,
            ok: Color::Green,
            err: Color::Red,
            key: Color::Cyan,
            brand: Color::Red,
            clusters: Color::Cyan,
            jobs: Color::Magenta,
            pipelines: Color::Green,
            warehouses: Color::Blue,
            catalog: rgb(0xFF8C42),
            grad_from: rgb3(0xFF3621),
            grad_to: rgb3(0xFFA046),
            bg: Color::Reset,
        },
    },
    Theme {
        id: "light",
        name: "Light",
        kind: ThemeKind::Light,
        origin: Origin::Builtin,
        keywords: "white bright",
        // Explicit darker shades that stay readable on a white background.
        palette: Palette {
            text: Color::Black,
            dim: rgb(0x6B7280),
            border: rgb(0x9CA3AF),
            warn: rgb(0xB45309),
            ok: rgb(0x15803D),
            err: rgb(0xB91C1C),
            key: rgb(0x0891B2),
            brand: rgb(0xDC2626),
            clusters: rgb(0x0891B2),
            jobs: rgb(0xA21CAF),
            pipelines: rgb(0x15803D),
            warehouses: rgb(0x1D4ED8),
            catalog: rgb(0xC2410C),
            grad_from: rgb3(0xB91C1C),
            grad_to: rgb3(0xC2410C),
            bg: rgb(0xFFFFFF),
        },
    },
    Theme {
        id: "catppuccin-mocha",
        name: "Catppuccin Mocha",
        kind: ThemeKind::Dark,
        origin: Origin::Builtin,
        keywords: "catppuccin pastel",
        palette: Palette {
            text: rgb(0xCDD6F4),
            dim: rgb(0x6C7086),
            border: rgb(0x585B70),
            warn: rgb(0xF9E2AF),
            ok: rgb(0xA6E3A1),
            err: rgb(0xF38BA8),
            key: rgb(0x89DCEB),
            brand: rgb(0xF38BA8),
            clusters: rgb(0x89DCEB),
            jobs: rgb(0xCBA6F7),
            pipelines: rgb(0xA6E3A1),
            warehouses: rgb(0x89B4FA),
            catalog: rgb(0xFAB387),
            grad_from: rgb3(0xF38BA8),
            grad_to: rgb3(0xFAB387),
            bg: rgb(0x1E1E2E),
        },
    },
    Theme {
        id: "catppuccin-macchiato",
        name: "Catppuccin Macchiato",
        kind: ThemeKind::Dark,
        origin: Origin::Builtin,
        keywords: "catppuccin pastel",
        palette: Palette {
            text: rgb(0xCAD3F5),
            dim: rgb(0x6E738D),
            border: rgb(0x5B6078),
            warn: rgb(0xEED49F),
            ok: rgb(0xA6DA95),
            err: rgb(0xED8796),
            key: rgb(0x91D7E3),
            brand: rgb(0xED8796),
            clusters: rgb(0x91D7E3),
            jobs: rgb(0xC6A0F6),
            pipelines: rgb(0xA6DA95),
            warehouses: rgb(0x8AADF4),
            catalog: rgb(0xF5A97F),
            grad_from: rgb3(0xED8796),
            grad_to: rgb3(0xF5A97F),
            bg: rgb(0x24273A),
        },
    },
    Theme {
        id: "catppuccin-frappe",
        name: "Catppuccin Frappé",
        kind: ThemeKind::Dark,
        origin: Origin::Builtin,
        keywords: "catppuccin pastel frappe",
        palette: Palette {
            text: rgb(0xC6D0F5),
            dim: rgb(0x737994),
            border: rgb(0x626880),
            warn: rgb(0xE5C890),
            ok: rgb(0xA6D189),
            err: rgb(0xE78284),
            key: rgb(0x99D1DB),
            brand: rgb(0xE78284),
            clusters: rgb(0x99D1DB),
            jobs: rgb(0xCA9EE6),
            pipelines: rgb(0xA6D189),
            warehouses: rgb(0x8CAAEE),
            catalog: rgb(0xEF9F76),
            grad_from: rgb3(0xE78284),
            grad_to: rgb3(0xEF9F76),
            bg: rgb(0x303446),
        },
    },
    Theme {
        id: "catppuccin-latte",
        name: "Catppuccin Latte",
        kind: ThemeKind::Light,
        origin: Origin::Builtin,
        keywords: "catppuccin pastel",
        palette: Palette {
            text: rgb(0x4C4F69),
            dim: rgb(0x8C8FA1),
            border: rgb(0xACB0BE),
            warn: rgb(0xDF8E1D),
            ok: rgb(0x40A02B),
            err: rgb(0xD20F39),
            key: rgb(0x04A5E5),
            brand: rgb(0xD20F39),
            clusters: rgb(0x04A5E5),
            jobs: rgb(0x8839EF),
            pipelines: rgb(0x40A02B),
            warehouses: rgb(0x1E66F5),
            catalog: rgb(0xFE640B),
            grad_from: rgb3(0xD20F39),
            grad_to: rgb3(0xFE640B),
            bg: rgb(0xEFF1F5),
        },
    },
    Theme {
        id: "gruvbox",
        name: "Gruvbox Dark",
        kind: ThemeKind::Dark,
        origin: Origin::Builtin,
        keywords: "gruvbox retro warm",
        palette: Palette {
            text: rgb(0xEBDBB2),
            dim: rgb(0x928374),
            border: rgb(0x665C54),
            warn: rgb(0xFABD2F),
            ok: rgb(0xB8BB26),
            err: rgb(0xFB4934),
            key: rgb(0x8EC07C),
            brand: rgb(0xFB4934),
            clusters: rgb(0x8EC07C),
            jobs: rgb(0xD3869B),
            pipelines: rgb(0xB8BB26),
            warehouses: rgb(0x83A598),
            catalog: rgb(0xFE8019),
            grad_from: rgb3(0xFB4934),
            grad_to: rgb3(0xFE8019),
            bg: rgb(0x282828),
        },
    },
    Theme {
        id: "gruvbox-light",
        name: "Gruvbox Light",
        kind: ThemeKind::Light,
        origin: Origin::Builtin,
        keywords: "gruvbox retro warm",
        palette: Palette {
            text: rgb(0x3C3836),
            dim: rgb(0x928374),
            border: rgb(0xBDAE93),
            warn: rgb(0xB57614),
            ok: rgb(0x79740E),
            err: rgb(0x9D0006),
            key: rgb(0x427B58),
            brand: rgb(0x9D0006),
            clusters: rgb(0x427B58),
            jobs: rgb(0x8F3F71),
            pipelines: rgb(0x79740E),
            warehouses: rgb(0x076678),
            catalog: rgb(0xAF3A03),
            grad_from: rgb3(0x9D0006),
            grad_to: rgb3(0xAF3A03),
            bg: rgb(0xFBF1C7),
        },
    },
    Theme {
        id: "dracula",
        name: "Dracula",
        kind: ThemeKind::Dark,
        origin: Origin::Builtin,
        keywords: "dracula purple vivid",
        palette: Palette {
            text: rgb(0xF8F8F2),
            dim: rgb(0x6272A4),
            border: rgb(0x44475A),
            warn: rgb(0xF1FA8C),
            ok: rgb(0x50FA7B),
            err: rgb(0xFF5555),
            key: rgb(0x8BE9FD),
            brand: rgb(0xFF5555),
            clusters: rgb(0x8BE9FD),
            jobs: rgb(0xFF79C6),
            pipelines: rgb(0x50FA7B),
            warehouses: rgb(0xBD93F9),
            catalog: rgb(0xFFB86C),
            grad_from: rgb3(0xFF5555),
            grad_to: rgb3(0xFFB86C),
            bg: rgb(0x282A36),
        },
    },
    Theme {
        id: "nord",
        name: "Nord",
        kind: ThemeKind::Dark,
        origin: Origin::Builtin,
        keywords: "nord arctic blue cool",
        palette: Palette {
            text: rgb(0xD8DEE9),
            dim: rgb(0x4C566A),
            border: rgb(0x434C5E),
            warn: rgb(0xEBCB8B),
            ok: rgb(0xA3BE8C),
            err: rgb(0xBF616A),
            key: rgb(0x88C0D0),
            brand: rgb(0xBF616A),
            clusters: rgb(0x88C0D0),
            jobs: rgb(0xB48EAD),
            pipelines: rgb(0xA3BE8C),
            warehouses: rgb(0x81A1C1),
            catalog: rgb(0xD08770),
            grad_from: rgb3(0xBF616A),
            grad_to: rgb3(0xD08770),
            bg: rgb(0x2E3440),
        },
    },
    Theme {
        id: "tokyo-night",
        name: "Tokyo Night",
        kind: ThemeKind::Dark,
        origin: Origin::Builtin,
        keywords: "tokyo night neon blue",
        palette: Palette {
            text: rgb(0xC0CAF5),
            dim: rgb(0x565F89),
            border: rgb(0x3B4261),
            warn: rgb(0xE0AF68),
            ok: rgb(0x9ECE6A),
            err: rgb(0xF7768E),
            key: rgb(0x7DCFFF),
            brand: rgb(0xF7768E),
            clusters: rgb(0x7DCFFF),
            jobs: rgb(0xBB9AF7),
            pipelines: rgb(0x9ECE6A),
            warehouses: rgb(0x7AA2F7),
            catalog: rgb(0xFF9E64),
            grad_from: rgb3(0xF7768E),
            grad_to: rgb3(0xFF9E64),
            bg: rgb(0x1A1B26),
        },
    },
    Theme {
        id: "rose-pine",
        name: "Rosé Pine",
        kind: ThemeKind::Dark,
        origin: Origin::Builtin,
        keywords: "rose pine muted",
        palette: Palette {
            text: rgb(0xE0DEF4),
            dim: rgb(0x6E6A86),
            border: rgb(0x403D52),
            warn: rgb(0xF6C177),
            ok: rgb(0x31748F),
            err: rgb(0xEB6F92),
            key: rgb(0x9CCFD8),
            brand: rgb(0xEB6F92),
            clusters: rgb(0x9CCFD8),
            jobs: rgb(0xC4A7E7),
            pipelines: rgb(0x31748F),
            warehouses: rgb(0x3E8FB0),
            catalog: rgb(0xEBBCBA),
            grad_from: rgb3(0xEB6F92),
            grad_to: rgb3(0xEBBCBA),
            bg: rgb(0x191724),
        },
    },
    Theme {
        id: "everforest",
        name: "Everforest Dark",
        kind: ThemeKind::Dark,
        origin: Origin::Builtin,
        keywords: "everforest green forest",
        palette: Palette {
            text: rgb(0xD3C6AA),
            dim: rgb(0x859289),
            border: rgb(0x475258),
            warn: rgb(0xDBBC7F),
            ok: rgb(0xA7C080),
            err: rgb(0xE67E80),
            key: rgb(0x83C092),
            brand: rgb(0xE67E80),
            clusters: rgb(0x83C092),
            jobs: rgb(0xD699B6),
            pipelines: rgb(0xA7C080),
            warehouses: rgb(0x7FBBB3),
            catalog: rgb(0xE69875),
            grad_from: rgb3(0xE67E80),
            grad_to: rgb3(0xE69875),
            bg: rgb(0x2D353B),
        },
    },
    Theme {
        id: "kanagawa",
        name: "Kanagawa",
        kind: ThemeKind::Dark,
        origin: Origin::Builtin,
        keywords: "kanagawa wave japanese ink",
        palette: Palette {
            text: rgb(0xDCD7BA),
            dim: rgb(0x727169),
            border: rgb(0x54546D),
            warn: rgb(0xE6C384),
            ok: rgb(0x98BB6C),
            err: rgb(0xC34043),
            key: rgb(0x7FB4CA),
            brand: rgb(0xC34043),
            clusters: rgb(0x7FB4CA),
            jobs: rgb(0x957FB8),
            pipelines: rgb(0x98BB6C),
            warehouses: rgb(0x7E9CD8),
            catalog: rgb(0xFFA066),
            grad_from: rgb3(0xC34043),
            grad_to: rgb3(0xFFA066),
            bg: rgb(0x1F1F28),
        },
    },
    Theme {
        id: "solarized-dark",
        name: "Solarized Dark",
        kind: ThemeKind::Dark,
        origin: Origin::Builtin,
        keywords: "solarized teal classic",
        palette: Palette {
            text: rgb(0x93A1A1),
            dim: rgb(0x586E75),
            border: rgb(0x073642),
            warn: rgb(0xB58900),
            ok: rgb(0x859900),
            err: rgb(0xDC322F),
            key: rgb(0x2AA198),
            brand: rgb(0xDC322F),
            clusters: rgb(0x2AA198),
            jobs: rgb(0xD33682),
            pipelines: rgb(0x859900),
            warehouses: rgb(0x268BD2),
            catalog: rgb(0xCB4B16),
            grad_from: rgb3(0xDC322F),
            grad_to: rgb3(0xCB4B16),
            bg: rgb(0x002B36),
        },
    },
    Theme {
        id: "one-dark",
        name: "One Dark",
        kind: ThemeKind::Dark,
        origin: Origin::Builtin,
        keywords: "one dark atom",
        palette: Palette {
            text: rgb(0xABB2BF),
            dim: rgb(0x5C6370),
            border: rgb(0x3E4451),
            warn: rgb(0xE5C07B),
            ok: rgb(0x98C379),
            err: rgb(0xE06C75),
            key: rgb(0x56B6C2),
            brand: rgb(0xE06C75),
            clusters: rgb(0x56B6C2),
            jobs: rgb(0xC678DD),
            pipelines: rgb(0x98C379),
            warehouses: rgb(0x61AFEF),
            catalog: rgb(0xD19A66),
            grad_from: rgb3(0xE06C75),
            grad_to: rgb3(0xD19A66),
            bg: rgb(0x282C34),
        },
    },
];
