#!/usr/bin/env python3
"""Generate src/theme/parks.rs from a checkout of pjhamera/national-parks-themes.

The parks repo authors each of the 63 US National Parks as ten OKLCH anchors
(bg fg accent red orange yellow green cyan blue purple) and derives a light
variant from them mathematically. databricks-tui's Palette wants thirteen
colours plus two gradient endpoints, all drawn from that same set, so the
mapping is mechanical.

This script reimplements the subset of the upstream Lua colour math that the
mapping needs, rather than adding a colour crate to the binary: the palettes
are constants, so they are computed once here and committed as Rust.

    scripts/gen_parks_themes.py                  # regenerate src/theme/parks.rs
    scripts/gen_parks_themes.py --verify         # regenerate, then check the
                                                 # result against upstream's own
                                                 # terminal exports
    scripts/gen_parks_themes.py --report         # print achieved contrast ratios

--verify is the real correctness gate. The parks repo commits fully-resolved
ghostty schemes for all 126 variants, generated by the Lua this file ports, and
eleven of the thirteen Palette fields appear verbatim in them. A drifted mix(),
a missing gamut clip or a wrong derive_light constant shows up there as an
exact-value diff rather than as a colour nobody notices.

The one deliberate divergence from upstream is the TUI tint applied to text,
dim and border -- see TINT_GAIN below for why a TUI that never paints a
background needs it. It runs after the upstream values are computed and
--verify still diffs those, so the gate above stays exactly as strong.
"""

from __future__ import annotations

import argparse
import math
import re
import subprocess
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# OKLCH, ported from lua/parks/palette/oklch.lua
#
# Kept deliberately close to the Lua, including the constants and the shape of
# the gamut search, so the two can be compared line by line when upstream moves.
# ---------------------------------------------------------------------------


def clamp(v: float, lo: float, hi: float) -> float:
    return min(max(v, lo), hi)


def cbrt(v: float) -> float:
    """Cube root that keeps the sign of negative inputs."""
    if v < 0:
        return -((-v) ** (1 / 3))
    return v ** (1 / 3)


def to_linear(c: float) -> float:
    if c <= 0.04045:
        return c / 12.92
    return ((c + 0.055) / 1.055) ** 2.4


def to_gamma(c: float) -> float:
    if c <= 0.0031308:
        return c * 12.92
    return 1.055 * (c ** (1 / 2.4)) - 0.055


def hex_to_rgb(hexstr: str) -> tuple[float, float, float]:
    s = hexstr.lstrip("#")
    if len(s) != 6 or not re.fullmatch(r"[0-9a-fA-F]{6}", s):
        raise ValueError(f"invalid hex color {hexstr!r}")
    return (
        int(s[0:2], 16) / 255,
        int(s[2:4], 16) / 255,
        int(s[4:6], 16) / 255,
    )


def rgb_to_hex(r: float, g: float, b: float) -> str:
    return "#%02x%02x%02x" % (
        math.floor(clamp(r, 0, 1) * 255 + 0.5),
        math.floor(clamp(g, 0, 1) * 255 + 0.5),
        math.floor(clamp(b, 0, 1) * 255 + 0.5),
    )


def rgb_to_oklab(r: float, g: float, b: float) -> tuple[float, float, float]:
    lr, lg, lb = to_linear(r), to_linear(g), to_linear(b)

    l = 0.4122214708 * lr + 0.5363325363 * lg + 0.0514459929 * lb
    m = 0.2119034982 * lr + 0.6806995451 * lg + 0.1073969566 * lb
    s = 0.0883024619 * lr + 0.2817188376 * lg + 0.6299787005 * lb

    l_, m_, s_ = cbrt(l), cbrt(m), cbrt(s)

    return (
        0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_,
        1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_,
        0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_,
    )


def oklab_to_rgb(L: float, a: float, b: float) -> tuple[float, float, float]:
    l_ = L + 0.3963377774 * a + 0.2158037573 * b
    m_ = L - 0.1055613458 * a - 0.0638541728 * b
    s_ = L - 0.0894841775 * a - 1.2914855480 * b

    l, m, s = l_ * l_ * l_, m_ * m_ * m_, s_ * s_ * s_

    return (
        to_gamma(4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s),
        to_gamma(-1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s),
        to_gamma(-0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s),
    )


class Lch:
    __slots__ = ("l", "c", "h")

    def __init__(self, l: float, c: float, h: float) -> None:
        self.l, self.c, self.h = l, c, h


def to_lch(hexstr: str) -> Lch:
    L, a, b = rgb_to_oklab(*hex_to_rgb(hexstr))
    c = math.sqrt(a * a + b * b)
    h = math.degrees(math.atan2(b, a))
    if h < 0:
        h += 360
    return Lch(L, c, h)


def in_gamut(l: float, c: float, h: float) -> bool:
    a = c * math.cos(math.radians(h))
    b = c * math.sin(math.radians(h))
    r, g, bl = oklab_to_rgb(l, a, b)
    eps = 1e-4
    return -eps <= r <= 1 + eps and -eps <= g <= 1 + eps and -eps <= bl <= 1 + eps


def to_hex(lch: Lch) -> str:
    """OKLCH back to hex, walking chroma down until the colour fits in sRGB.

    Clipping RGB instead would shift hue, which is the one thing the parks
    palettes are not allowed to do.
    """
    l = clamp(lch.l, 0, 1)
    h = lch.h % 360
    c = max(lch.c, 0)

    if not in_gamut(l, c, h):
        lo, hi = 0.0, c
        for _ in range(24):
            mid = (lo + hi) / 2
            if in_gamut(l, mid, h):
                lo = mid
            else:
                hi = mid
        c = lo

    a = c * math.cos(math.radians(h))
    b = c * math.sin(math.radians(h))
    return rgb_to_hex(*oklab_to_rgb(l, a, b))


def adjust(hexstr: str, fn) -> str:
    return to_hex(fn(to_lch(hexstr)))


def mix(a: str, b: str, t: float) -> str:
    """Blend in OKLab -- *not* OKLCH. Interpolating chroma and hue instead
    would swing through unrelated hues on the way between two colours."""
    t = clamp(t, 0, 1)
    l1, a1, b1 = rgb_to_oklab(*hex_to_rgb(a))
    l2, a2, b2 = rgb_to_oklab(*hex_to_rgb(b))
    r, g, bl = oklab_to_rgb(l1 + (l2 - l1) * t, a1 + (a2 - a1) * t, b1 + (b2 - b1) * t)
    return rgb_to_hex(clamp(r, 0, 1), clamp(g, 0, 1), clamp(bl, 0, 1))


def tint(hexstr: str, gain: float, floor: float, ceil: float) -> str:
    """Raise a near-neutral colour's chroma without touching its hue.

    Scaling rather than assigning keeps upstream's relative intent -- Grand
    Canyon was authored richer than Yosemite and stays richer -- while the floor
    guarantees no park lands back in grey and the ceiling stops the loudest
    parks from turning body text into an accent.
    """
    lch = to_lch(hexstr)
    lch.c = clamp(lch.c * gain, floor, ceil)
    return to_hex(lch)


def luminance(hexstr: str) -> float:
    r, g, b = hex_to_rgb(hexstr)
    return 0.2126 * to_linear(r) + 0.7152 * to_linear(g) + 0.0722 * to_linear(b)


def contrast(a: str, b: str) -> float:
    la, lb = luminance(a), luminance(b)
    if la < lb:
        la, lb = lb, la
    return (la + 0.05) / (lb + 0.05)


def ensure_contrast(fg: str, bg: str, ratio: float) -> str:
    """Nudge `fg` along lightness until it clears `ratio` against `bg`.

    Best-effort, not a guarantee: it gives up after 50 steps or at the ends of
    the lightness range and returns the best it reached.
    """
    if contrast(fg, bg) >= ratio:
        return fg

    lch = to_lch(fg)
    bg_l = to_lch(bg).l
    step = 0.02 if bg_l < 0.5 else -0.02
    best, best_ratio = fg, contrast(fg, bg)

    for _ in range(50):
        lch.l = clamp(lch.l + step, 0, 1)
        candidate = to_hex(lch)
        got = contrast(candidate, bg)
        if got > best_ratio:
            best, best_ratio = candidate, got
        if got >= ratio:
            return candidate
        if lch.l <= 0 or lch.l >= 1:
            break

    return best


# ---------------------------------------------------------------------------
# Reading the parks repo
# ---------------------------------------------------------------------------

REQUIRED = ["bg", "fg", "accent", "red", "orange", "yellow", "green", "cyan", "blue", "purple"]

# Contrast floors, from build.lua's M.CONTRAST.
TEXT_CONTRAST = 7.0
MUTED_CONTRAST = 4.5
ACCENT_CONTRAST = 4.5

# --- The TUI tint (databricks-tui only, not upstream) ----------------------
#
# Upstream authors `fg` for a terminal that also paints its `bg`, so a park's
# character can live in the background and the foreground can stay near-neutral.
# This TUI never paints a background -- it inherits the terminal's -- so the
# only thing on screen carrying a park's identity is its foreground, and text /
# dim / border are most of the pixels. Shipped untouched, all 63 parks render
# body text at OKLCH chroma 0.017 on average, which is grey: the palettes are
# distinguishable in the swatch strip and nowhere else.
#
# The fix keeps each park's authored *hue* -- it already tracks that park's own
# bg hue closely -- and only raises its chroma, so text reads as iced blue on
# Denali and sandstone on Zion. For calibration, the built-ins nobody complains
# about sit at chroma 0.039 (kanagawa) to 0.061 (tokyo-night); the floor and
# ceiling below bracket that range.
#
# Applied after the upstream values are computed, never before: --verify still
# diffs the pre-tint colours against upstream's own exports.
TINT_GAIN = 2.4  # multiplier on the park's authored chroma
TINT_FLOOR = 0.030  # lift the near-neutral parks (Yosemite, Gateway Arch) into visibility
TINT_CEIL = 0.060  # keep the already-saturated parks (Zion, Arches) from shouting

# derive_light's targets, from build.lua's LIGHT table.
LIGHT_BG_L = 0.955
LIGHT_BG_CHROMA = 2.2
LIGHT_BG_CHROMA_CAP = 0.020
LIGHT_FG_L = 0.30
LIGHT_FG_CHROMA_CAP = 0.055
LIGHT_ACCENT_L = 0.52
LIGHT_ACCENT_SPREAD = 0.85
LIGHT_ACCENT_CHROMA = 1.12

ENTRY_RE = re.compile(
    r'\{\s*slug\s*=\s*"([^"]+)"\s*,\s*name\s*=\s*"([^"]+)"\s*,\s*'
    r'dir\s*=\s*"([^"]+)"\s*,\s*states\s*=\s*\{([^}]*)\}\s*,?\s*\}'
)


class Park:
    def __init__(self, slug, name, dir_, states, blurb, established, anchors):
        self.slug, self.name, self.dir = slug, name, dir_
        self.states, self.blurb = states, blurb
        self.established, self.anchors = established, anchors


def read_registry(repo: Path) -> list[tuple[str, str, str, list[str]]]:
    src = (repo / "lua/parks/palette/registry.lua").read_text()
    out = []
    for slug, name, dir_, states in ENTRY_RE.findall(src):
        out.append((slug, name, dir_, re.findall(r'"([^"]+)"', states)))
    return out


def read_park(repo: Path, slug: str, name: str, dir_: str, states: list[str]) -> Park:
    # Slugs are hyphenated but Lua module files are not: gates-of-the-arctic
    # lives at alaska/gates_of_the_arctic.lua.
    path = repo / "lua/parks/parks" / dir_ / f"{slug.replace('-', '_')}.lua"
    if not path.exists():
        raise SystemExit(f"missing palette file for {slug}: {path}")
    src = path.read_text()

    body = re.search(r"\bdark\s*=\s*\{(.*?)\n  \}", src, re.S)
    if not body:
        raise SystemExit(f"{slug}: could not find the `dark` anchor table")

    anchors = dict(re.findall(r'^\s*(\w+)\s*=\s*"(#[0-9a-fA-F]{6})"', body.group(1), re.M))
    missing = [k for k in REQUIRED if k not in anchors]
    if missing:
        raise SystemExit(f"{slug}: missing required anchors {missing}")
    extra = [k for k in anchors if k not in REQUIRED]
    if extra:
        # derive_light averages over every non-bg/fg anchor, so an unexpected
        # one would silently move every light colour.
        raise SystemExit(f"{slug}: unexpected extra anchors {extra}")

    if re.search(r"^\s*light\s*=\s*\{", src, re.M):
        raise SystemExit(
            f"{slug}: declares a `light = {{}}` override, which this generator "
            f"does not implement -- add it before regenerating"
        )

    blurb_m = re.search(r'^\s*blurb\s*=\s*"([^"]*)"', src, re.M)
    est_m = re.search(r"^\s*established\s*=\s*(\d+)", src, re.M)
    return Park(
        slug,
        name,
        dir_,
        states,
        blurb_m.group(1) if blurb_m else "",
        est_m.group(1) if est_m else "",
        anchors,
    )


def derive_light(dark: dict[str, str]) -> dict[str, str]:
    """Port of build.lua's derive_light. Hue is carried over untouched."""
    light = {}

    def bg_fn(lch):
        lch.l = LIGHT_BG_L
        lch.c = min(lch.c * LIGHT_BG_CHROMA, LIGHT_BG_CHROMA_CAP)
        return lch

    def fg_fn(lch):
        lch.l = LIGHT_FG_L
        lch.c = min(lch.c, LIGHT_FG_CHROMA_CAP)
        return lch

    light["bg"] = adjust(dark["bg"], bg_fn)
    light["fg"] = adjust(dark["fg"], fg_fn)

    accents = [n for n in dark if n not in ("bg", "fg")]
    mean_l = (
        sum(to_lch(dark[n]).l for n in accents) / len(accents) if accents else LIGHT_ACCENT_L
    )

    for name in accents:
        def accent_fn(lch, _mean=mean_l):
            lch.l = LIGHT_ACCENT_L - (lch.l - _mean) * LIGHT_ACCENT_SPREAD
            lch.c = lch.c * LIGHT_ACCENT_CHROMA
            return lch

        light[name] = adjust(dark[name], accent_fn)

    return light


# ---------------------------------------------------------------------------
# Anchors -> Palette
# ---------------------------------------------------------------------------


class Variant:
    """One park in one variant: the Palette fields plus the few upstream
    intermediates --verify needs."""

    def __init__(self, park: Park, kind: str) -> None:
        self.park, self.kind = park, kind
        a = park.anchors if kind == "dark" else derive_light(park.anchors)
        self.anchors = a
        bg = a["bg"]

        # build_text: the muted tone blends the *raw* fg, then is floored.
        self.bg = bg
        self.text_upstream = ensure_contrast(a["fg"], bg, TEXT_CONTRAST)
        self.dim_upstream = ensure_contrast(mix(a["fg"], bg, 0.32), bg, MUTED_CONTRAST)
        # build.lua takes the border off the floored fg, not the raw anchor.
        self.border_upstream = mix(self.text_upstream, bg, 0.62)

        # The TUI tint: park identity has to survive in the foreground here,
        # because nothing paints `bg`. Chroma first, then re-floor -- raising
        # chroma can cost a little contrast, and the floors outrank the tint.
        # `to_hex` walks chroma back down when a hue cannot hold the target at
        # this lightness, so a gamut-bound blue simply lands as blue as it gets.
        self.text = ensure_contrast(
            tint(self.text_upstream, TINT_GAIN, TINT_FLOOR, TINT_CEIL), bg, TEXT_CONTRAST
        )
        self.dim = ensure_contrast(
            tint(self.dim_upstream, TINT_GAIN, TINT_FLOOR, TINT_CEIL), bg, MUTED_CONTRAST
        )
        # Borders stay derived from the tinted text, as upstream derives theirs
        # from the floored fg, so the chrome carries the same tone as the body.
        self.border = mix(self.text, bg, 0.62)

        acc = {n: ensure_contrast(a[n], bg, ACCENT_CONTRAST) for n in REQUIRED[2:]}
        self.acc = acc

        self.err, self.ok, self.warn, self.key = acc["red"], acc["green"], acc["yellow"], acc["cyan"]
        self.brand = acc["accent"]
        self.clusters, self.jobs = acc["cyan"], acc["purple"]
        self.pipelines, self.warehouses = acc["green"], acc["blue"]
        self.catalog = acc["orange"]
        self.grad_from, self.grad_to = acc["accent"], acc["orange"]

        # Not a Palette field; cursor-color in the exports pins `brand`.
        dir_ = 1 if kind == "dark" else -1

        def bright(lch):
            lch.l = min(max(lch.l + 0.09 * dir_, 0), 1)
            lch.c = lch.c * 1.06
            return lch

        self.accent_bright = adjust(self.brand, bright)

    @property
    def id(self) -> str:
        return f"parks-{self.park.slug}" + ("-light" if self.kind == "light" else "")

    @property
    def display_name(self) -> str:
        return self.park.name + (" Light" if self.kind == "light" else "")

    @property
    def keywords(self) -> str:
        words = [w.replace("_", " ") for w in self.park.states]
        words += re.sub(r"[^a-z0-9 ]", " ", self.park.blurb.lower()).split()
        if self.park.established:
            words.append(self.park.established)
        seen, out = set(), []
        for w in words:
            if w and w not in seen:
                seen.add(w)
                out.append(w)
        return " ".join(out)


def build_all(repo: Path) -> list[Variant]:
    registry = read_registry(repo)
    if len(registry) != 63:
        raise SystemExit(f"expected 63 parks in the registry, found {len(registry)}")

    variants = []
    for slug, name, dir_, states in registry:
        park = read_park(repo, slug, name, dir_, states)
        variants.append(Variant(park, "dark"))
        variants.append(Variant(park, "light"))

    if len(variants) != 126:
        raise SystemExit(f"expected 126 variants, built {len(variants)}")

    ids = [v.id for v in variants]
    if len(set(ids)) != len(ids):
        dupes = sorted({i for i in ids if ids.count(i) > 1})
        raise SystemExit(f"duplicate theme ids: {dupes}")
    pattern = re.compile(r"^parks-[a-z0-9-]+(-light)?$")
    bad = [i for i in ids if not pattern.match(i)]
    if bad:
        raise SystemExit(f"theme ids do not match the expected pattern: {bad}")

    # A floor sanity gate, deliberately below the 7.0 that ensure_contrast only
    # best-efforts -- this catches a broken port, not a stubborn park.
    for v in variants:
        t, d = contrast(v.text, v.bg), contrast(v.dim, v.bg)
        if t < 4.5:
            raise SystemExit(f"{v.id}: text contrast {t:.2f} is below the 4.5 floor")
        if d < 3.0:
            raise SystemExit(f"{v.id}: dim contrast {d:.2f} is below the 3.0 floor")

    return variants


# ---------------------------------------------------------------------------
# Emitting Rust
# ---------------------------------------------------------------------------

FIELDS = [
    "text", "dim", "border", "warn", "ok", "err", "key", "brand",
    "clusters", "jobs", "pipelines", "warehouses", "catalog",
]


def rust_hex(hexstr: str) -> str:
    return "0x" + hexstr.lstrip("#").upper()


def emit(variants: list[Variant], rev: str) -> str:
    out = [
        "// @generated by scripts/gen_parks_themes.py -- do not edit.",
        "//",
        "// Regenerate with:",
        "//     scripts/gen_parks_themes.py --parks-repo ../national-parks-themes --verify",
        "//",
        "// Source: https://github.com/pjhamera/national-parks-themes",
        "",
        "use super::{rgb, rgb3, Origin, Palette, Theme, ThemeKind};",
        "",
        "/// The parks-repo commit these palettes were generated from, so drift is",
        "/// detectable without re-deriving every colour.",
        f'pub const PARKS_SOURCE_REV: &str = "{rev}";',
        "",
        "pub static PARKS: &[Theme] = &[",
    ]

    for v in variants:
        kind = "Dark" if v.kind == "dark" else "Light"
        out += [
            "    Theme {",
            f'        id: "{v.id}",',
            f'        name: "{escape(v.display_name)}",',
            f"        kind: ThemeKind::{kind},",
            "        origin: Origin::Parks,",
            f'        keywords: "{escape(v.keywords)}",',
            "        palette: Palette {",
        ]
        for f in FIELDS:
            out.append(f"            {f}: rgb({rust_hex(getattr(v, f))}),")
        out.append(f"            grad_from: rgb3({rust_hex(v.grad_from)}),")
        out.append(f"            grad_to: rgb3({rust_hex(v.grad_to)}),")
        out.append(f"            bg: rgb({rust_hex(v.bg)}),")
        out += ["        },", "    },"]

    out += ["];", ""]
    return "\n".join(out)


def rustfmt(text: str) -> str:
    """Format through rustfmt so `cargo fmt` never rewrites what we emit --
    otherwise --check reports drift after every unrelated `cargo fmt`."""
    try:
        done = subprocess.run(
            ["rustfmt", "--edition", "2021", "--emit", "stdout"],
            input=text, capture_output=True, text=True, check=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError) as e:
        print(f"warning: rustfmt unavailable ({e}); emitting unformatted", file=sys.stderr)
        return text
    # rustfmt --emit stdout prefixes a filename banner when reading stdin.
    out = done.stdout
    if out.startswith("<stdin>:\n"):
        out = out[len("<stdin>:\n"):]
    return out


def escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


# ---------------------------------------------------------------------------
# Verification against upstream's own exports
# ---------------------------------------------------------------------------

# generated field -> ghostty key. Eleven of the thirteen Palette fields appear
# verbatim in files upstream produced with its own Lua. text/dim/border are
# compared pre-tint (`*_upstream`), so the tint cannot mask a ported-math bug.
GHOSTTY_MAP = [
    ("bg", "background"),
    ("text_upstream", "foreground"),
    ("dim_upstream", "palette 7"),
    ("border_upstream", "split-divider-color"),
    ("err", "palette 9"),
    ("ok", "palette 10"),
    ("warn", "palette 11"),
    ("warehouses", "palette 12"),
    ("jobs", "palette 13"),
    ("key", "palette 14"),
    ("accent_bright", "cursor-color"),
]


def parse_ghostty(path: Path) -> dict[str, str]:
    got = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        m = re.match(r"palette\s*=\s*(\d+)\s*=\s*(#[0-9a-fA-F]{6})", line)
        if m:
            got[f"palette {m.group(1)}"] = m.group(2).lower()
            continue
        m = re.match(r"([a-z-]+)\s*=\s*(#[0-9a-fA-F]{6})", line)
        if m:
            got[m.group(1)] = m.group(2).lower()
    return got


def verify(variants: list[Variant], repo: Path) -> int:
    mismatches, checked, skipped = 0, 0, 0
    for v in variants:
        path = repo / "terminal/ghostty" / v.id
        if not path.exists():
            print(f"  ! no ghostty export for {v.id}", file=sys.stderr)
            skipped += 1
            continue
        got = parse_ghostty(path)
        for field, key in GHOSTTY_MAP:
            if key not in got:
                print(f"  ! {v.id}: export has no {key!r}", file=sys.stderr)
                mismatches += 1
                continue
            mine = getattr(v, field).lower()
            if mine != got[key]:
                print(
                    f"  MISMATCH {v.id:<34} {field:<14} ours={mine} upstream={got[key]} ({key})",
                    file=sys.stderr,
                )
                mismatches += 1
            checked += 1

    print(f"verify: {checked} values checked across {len(variants) - skipped} themes, "
          f"{mismatches} mismatches")
    return mismatches


def report(variants: list[Variant]) -> None:
    """Contrast per theme, plus the text chroma the tint is there to move."""
    print(
        f"{'theme':<34} {'text':>6} {'dim':>6} {'brand':>6} "
        f"{'txtC':>6} {'was':>6} {'worst accent':>13}"
    )
    for v in variants:
        accents = {n: contrast(c, v.bg) for n, c in v.acc.items()}
        worst = min(accents.items(), key=lambda kv: kv[1])
        print(
            f"{v.id:<34} {contrast(v.text, v.bg):>6.2f} {contrast(v.dim, v.bg):>6.2f} "
            f"{contrast(v.brand, v.bg):>6.2f} {to_lch(v.text).c:>6.3f} "
            f"{to_lch(v.text_upstream).c:>6.3f} {worst[1]:>7.2f} {worst[0]}"
        )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--parks-repo",
        type=Path,
        default=Path(__file__).resolve().parent.parent.parent / "national-parks-themes",
        help="checkout of pjhamera/national-parks-themes (default: ../national-parks-themes)",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "src/theme/parks.rs",
    )
    ap.add_argument("--verify", action="store_true", help="diff against upstream's ghostty exports")
    ap.add_argument("--report", action="store_true", help="print achieved contrast ratios")
    ap.add_argument("--check", action="store_true", help="fail if the output file is out of date")
    args = ap.parse_args()

    repo = args.parks_repo.resolve()
    if not (repo / "lua/parks/palette/registry.lua").exists():
        raise SystemExit(f"not a parks checkout: {repo}")

    rev = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "HEAD"],
        capture_output=True, text=True, check=True,
    ).stdout.strip()

    variants = build_all(repo)
    text = rustfmt(emit(variants, rev))

    if args.check:
        current = args.out.read_text() if args.out.exists() else ""
        if current != text:
            print(f"{args.out} is out of date -- rerun {Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"{args.out} is up to date")
    else:
        args.out.write_text(text)
        print(f"wrote {args.out}: {len(variants)} themes from {repo.name}@{rev[:8]}")

    if args.report:
        report(variants)

    if args.verify:
        if verify(variants, repo) > 0:
            return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
